export const ROLE_CONSTANTS = {
  SUPMANAGER: 'SUPMANAGER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

export const ROLE_LEVEL = {
  [ROLE_CONSTANTS.EMPLOYEE]: 1,
  [ROLE_CONSTANTS.MANAGER]: 2,
  [ROLE_CONSTANTS.ADMIN]: 3,
  [ROLE_CONSTANTS.SUPMANAGER]: 4,
};

ROLE_CONSTANTS.ROLE_LEVEL = ROLE_LEVEL;
